# Create mysql server based on the official image from the dockerhub
FROM mysql:5
# Add a database & root password
ENV MYSQL_DATABASE=cnab_desafio
ENV MYSQL_ROOT_PASSWORD=abc123
ENV MYSQL_ROOT_USER=root
